SELECT 'customers' AS table_name, COUNT(*) AS row_count
FROM customers

UNION ALL

SELECT 'products', COUNT(*)
FROM products

UNION ALL

SELECT 'orders', COUNT(*)
FROM orders

UNION ALL

SELECT 'order_items', COUNT(*)
FROM order_items;

SELECT customers FROM customers
ORDER BY income DESC
LIMIT 10

-- number of customers in each state, highest count first.
SELECT state, COUNT(*) AS cutomer_count
FROM customers
GROUP BY state
ORDER BY cutomer_count DESC;

-- average income for each marital status
SELECT Marital_Status , AVG(income) AS avg_income
FROM customers
GROUP BY marital_Status
ORDER BY avg_income DESC

-- total revenue generated by each shipping city
SELECT shipping_city , SUM(total_order_value) AS Total_renv
FROM orders
GROUP BY shipping_city
ORDER BY Total_renv DESC;

-- customers who have placed more than 10 orders
SELECT c.customer_id , c.first_name,c.last_name , COUNT(o.order_id) AS total_order
FROM customers c JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id , c.first_name , c.last_name
HAVING COUNT(o.order_id) > 10
  
-- , top 10 customers by total spending
SELECT c.customer_id , c.first_name,c.last_name , SUM(o.total_order_value)  AS total_sepnding
FROM customers c Join orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id , c.first_name , c.last_name
ORDER BY total_sepnding DESC
limit 10